# Generated by Django 5.2.8 on 2025-12-01 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colormania', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='carrito',
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=150)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='colormania.pedido')),
            ],
        ),
    ]
