# Generated by Django 5.2.8 on 2025-12-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colormania', '0002_remove_pedido_carrito_itempedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=128),
        ),
    ]
